[package]
name = 'SatayLiquidswapBlocks'
version = '1.0.0'

[addresses]
liquidswap_blocks = "0x659d53b22ebb61ef1f64d28698b8117f65136d8bb211d6d22f54d5064eec08f5"

[dependencies.LiquidswapRouterV2]
git = 'https://github.com/pontem-network/liquidswap.git'
rev = 'main'
subdir = 'liquidswap_router_v2'