[package]
name = 'SatayLiquidswapBlocks'
version = '1.0.0'

[addresses]
satay_blocks = "0xe3eaddfcc4d7436d26fef92ee39685ef176e3513dc736d116129ce055c07afac"

[dependencies.LiquidswapRouterV2]
git = 'https://github.com/pontem-network/liquidswap.git'
rev = 'main'
subdir = 'liquidswap_router_v2'