[package]
name = 'SatayTortugaBlocks'
version = '1.0.0'

[addresses]
satay = "0x659d53b22ebb61ef1f64d28698b8117f65136d8bb211d6d22f54d5064eec08f5"

[dependencies.HippoAggregator]
git = 'https://github.com/hippospace/hippo-agg-interface'
rev = 'main'

[dependencies.tortuga]
git = 'https://github.com/satay-protocol/partner-interfaces'
rev = 'testnet'
subdir = 'tortuga-staking-interface'



[dependencies.SatayUtilityBlocks]
local = '../utility-blocks'
