[package]
name = 'SatayTortugaBlocks'
version = '1.0.0'

[addresses]
satay_blocks = "0xe3eaddfcc4d7436d26fef92ee39685ef176e3513dc736d116129ce055c07afac"

[dependencies.HippoAggregator]
git = 'https://github.com/satay-protocol/hippo-aggregator'
rev = 'main'

[dependencies.TortugaGovernance]
git = 'https://github.com/satay-protocol/partner-interfaces'
rev = 'mainnet'
subdir = 'tortuga/tortuga-governance'

[dependencies.SatayUtilityBlocks]
local = '../utility-blocks'
