[package]
name = 'SatayLiquidswapBricks'
version = '1.0.0'

[addresses]
liquidswap_bricks = "0xa063aa74aeb7aac297161df445de42d99e2e9ac0d560af9500b2db29f2b8c4d6"

[dependencies.LiquidswapRouterV2]
git = 'https://github.com/pontem-network/liquidswap.git'
rev = 'main'
subdir = 'liquidswap_router_v2'