[package]
name = 'SatayAriesBlocks'
version = '1.0.0'

[addresses]
satay_blocks = "0xe3eaddfcc4d7436d26fef92ee39685ef176e3513dc736d116129ce055c07afac"

[dependencies.Aries]
git = 'https://github.com/satay-protocol/partner-interfaces'
rev = 'mainnet'
subdir = 'aries-interface'