[package]
name = 'SatayDittoBlocks'
version = '1.0.0'

[addresses]
satay_blocks = "0xe3eaddfcc4d7436d26fef92ee39685ef176e3513dc736d116129ce055c07afac"

[dependencies.HippoAggregator]
git = 'https://github.com/hippospace/hippo-agg-interface'
rev = 'main'

[dependencies.ditto-staking]
git = 'https://github.com/satay-protocol/ditto-interface'
rev = 'testnet'
subdir = 'ditto-staking-interface'